spring.application.name=class-6_Product_Shop

spring.datasource.url=jdbc:mysql://localhost:3306/pdbsm26
spring.datasource.username=root
spring.datasource.password=seucse613

spring.jpa.hibernate.ddl-auto=update


